# Generated by Django 4.2.7 on 2026-02-01 08:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='نام کاربری')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="شماره تلفن باید در فرمت: '+999999999' باشد. حداکثر 15 رقم مجاز است.", regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تلفون')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('father_name', models.CharField(blank=True, max_length=255, verbose_name='نام پدر')),
                ('gender', models.CharField(choices=[('male', 'مذکر'), ('female', 'مونث')], default='male', max_length=10, verbose_name='جنسیت')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'مدیر اصلی'), ('ADMIN', 'مدیر'), ('TEACHER', 'استاد'), ('STUDENT', 'دانش\u200cآموز')], default='STUDENT', max_length=20, verbose_name='نقش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('approval_status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت تایید')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='عکس پروفایل')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='تایید شده توسط')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('permission_type', models.CharField(choices=[('can_view_students', 'مشاهده دانش\u200cآموزان'), ('can_create_students', 'ایجاد دانش\u200cآموز'), ('can_edit_students', 'ویرایش دانش\u200cآموز'), ('can_delete_students', 'حذف دانش\u200cآموز'), ('can_approve_students', 'تایید دانش\u200cآموزان'), ('can_view_teachers', 'مشاهده اساتید'), ('can_create_teachers', 'ایجاد استاد'), ('can_edit_teachers', 'ویرایش استاد'), ('can_delete_teachers', 'حذف استاد'), ('can_manage_classes', 'مدیریت صنوف'), ('can_manage_subjects', 'مدیریت مضامین'), ('can_manage_semesters', 'مدیریت سمسترها'), ('can_view_grades', 'مشاهده نمرات'), ('can_edit_grades', 'ویرایش نمرات'), ('can_view_attendance', 'مشاهده حاضری'), ('can_mark_attendance', 'ثبت حاضری'), ('can_view_documents', 'مشاهده اسناد'), ('can_upload_documents', 'بارگذاری اسناد'), ('can_delete_documents', 'حذف اسناد'), ('can_view_reports', 'مشاهده گزارشات'), ('can_configure_system', 'تنظیمات سیستم')], max_length=50, verbose_name='نوع دسترسی')),
                ('is_granted', models.BooleanField(default=False, verbose_name='اعطا شده')),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_permissions', to=settings.AUTH_USER_MODEL, verbose_name='مدیر')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='اعطا شده توسط')),
            ],
            options={
                'verbose_name': 'دسترسی مدیر',
                'verbose_name_plural': 'دسترسی\u200cهای مدیران',
                'unique_together': {('admin', 'permission_type')},
            },
        ),
    ]
