# Generated by Django 4.2.7 on 2026-02-01 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('father_name', models.CharField(blank=True, max_length=255, verbose_name='نام پدر')),
                ('grandfather_name', models.CharField(blank=True, max_length=255, verbose_name='نام پدر کلان')),
                ('id_number', models.CharField(blank=True, max_length=100, verbose_name='نمبر تذکره')),
                ('exam_number', models.CharField(blank=True, max_length=100, verbose_name='نمبر امتحان کانکور')),
                ('gender', models.CharField(choices=[('male', 'مذکر'), ('female', 'مونث')], default='male', max_length=10, verbose_name='جنسیت')),
                ('current_address', models.TextField(blank=True, verbose_name='نشانی فعلی')),
                ('permanent_address', models.TextField(blank=True, verbose_name='نشانی دایمی')),
                ('mobile_number', models.CharField(blank=True, max_length=20, verbose_name='شماره موبایل')),
                ('emergency_contact', models.CharField(blank=True, max_length=20, verbose_name='تماس اضطراری')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='تایم آغاز')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='تایم ختم')),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='عکس')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.schoolclass', verbose_name='صنف')),
                ('semesters', models.ManyToManyField(blank=True, related_name='students', to='academics.semester', verbose_name='سمسترها')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دانش\u200cآموز',
                'verbose_name_plural': 'دانش\u200cآموزان',
                'ordering': ['-created_at'],
            },
        ),
    ]
