# Generated by Codex on 2026-02-05

from django.db import migrations, models
import django.db.models.deletion


def _column_exists(schema_editor, table, column):
    vendor = schema_editor.connection.vendor
    cursor = schema_editor.connection.cursor()
    if vendor == 'sqlite':
        cursor.execute(f"PRAGMA table_info('{table}')")
        return column in [row[1] for row in cursor.fetchall()]
    try:
        desc = schema_editor.connection.introspection.get_table_description(cursor, table)
        return column in [c.name for c in desc]
    except Exception:
        return False


def add_subject_level_column(apps, schema_editor):
    if _column_exists(schema_editor, 'core_subject', 'level_id'):
        return
    schema_editor.execute('ALTER TABLE "core_subject" ADD COLUMN "level_id" bigint NULL')


def add_subject_period_column(apps, schema_editor):
    if _column_exists(schema_editor, 'core_subject', 'period_id'):
        return
    schema_editor.execute('ALTER TABLE "core_subject" ADD COLUMN "period_id" bigint NULL')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_schoolclass_period_fix'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_subject_level_column, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='subject',
                    name='level',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.studylevel', verbose_name='سطح آموزشی'),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_subject_period_column, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='subject',
                    name='period',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.courseperiod', verbose_name='دوره'),
                ),
            ],
        ),
    ]
