# Generated by Django 4.2.7 on 2026-02-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_student_teacher_behavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercontract',
            name='contract_number',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='شماره قرارداد'),
        ),
    ]
