# Generated by Django 4.2.7 on 2026-02-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_student_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره سرتفیکت'),
        ),
    ]
