# Generated by Django 4.2.7 on 2026-02-01 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='شماره سمستر')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='نام سمستر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سمستر',
                'verbose_name_plural': 'سمسترها',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('name', models.CharField(max_length=255, verbose_name='نام مضمون')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد مضمون')),
                ('credits', models.PositiveSmallIntegerField(default=3, verbose_name='واحد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.semester', verbose_name='سمستر مربوطه')),
            ],
            options={
                'verbose_name': 'مضمون',
                'verbose_name_plural': 'مضامین',
                'ordering': ['semester__number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام صنف')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='academics.semester', verbose_name='سمستر')),
            ],
            options={
                'verbose_name': 'صنف',
                'verbose_name_plural': 'صنوف',
                'ordering': ['name'],
            },
        ),
    ]
