# Generated by Django 4.2.7 on 2026-02-01 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0001_initial'),
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب'), ('late', 'تاخیر'), ('leave', 'مرخصی')], default='present', max_length=20, verbose_name='وضعیت')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='زمان ورود')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='زمان خروج')),
                ('remarks', models.TextField(blank=True, verbose_name='یادداشت')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_teacher_attendances', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='teachers.teacher', verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'حاضری استاد',
                'verbose_name_plural': 'حاضری اساتید',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('teacher', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب'), ('late', 'تاخیر'), ('excused', 'مرخصی')], default='present', max_length=20, verbose_name='وضعیت')),
                ('remarks', models.TextField(blank=True, verbose_name='یادداشت')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_student_attendances', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attendances', to='academics.schoolclass', verbose_name='صنف')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student', verbose_name='دانش\u200cآموز')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attendances', to='academics.subject', verbose_name='مضمون')),
            ],
            options={
                'verbose_name': 'حاضری دانش\u200cآموز',
                'verbose_name_plural': 'حاضری دانش\u200cآموزان',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('student', 'date', 'subject')},
            },
        ),
    ]
