# Generated by Django 4.2.7 on 2026-02-01 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('name', models.CharField(max_length=255, verbose_name='نام و تخلص استاد')),
                ('father_name', models.CharField(blank=True, max_length=255, verbose_name='نام پدر')),
                ('id_number', models.CharField(blank=True, max_length=100, verbose_name='نمبر تذکره')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='male', max_length=10, verbose_name='جنسیت')),
                ('current_address', models.TextField(blank=True, verbose_name='سکونت فعلی')),
                ('permanent_address', models.TextField(blank=True, verbose_name='سکونت اصلی')),
                ('mobile_number', models.CharField(blank=True, max_length=20, verbose_name='شماره موبایل')),
                ('emergency_contact', models.CharField(blank=True, max_length=20, verbose_name='تماس اضطراری')),
                ('education_level', models.CharField(choices=[('p', 'چهارده پاس'), ('b', 'لیسانس'), ('m', 'ماستر'), ('d', 'دوکتور')], default='b', max_length=2, verbose_name='سویه تحصیلی')),
                ('specialization', models.CharField(blank=True, max_length=255, verbose_name='تخصص')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='عکس')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام')),
                ('classes', models.ManyToManyField(blank=True, related_name='teachers', to='academics.schoolclass', verbose_name='صنوف')),
                ('semesters', models.ManyToManyField(blank=True, related_name='teachers', to='academics.semester', verbose_name='سمسترها')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='academics.subject', verbose_name='مضامین')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
                'ordering': ['-created_at'],
            },
        ),
    ]
