# Generated by Django 4.2.7 on 2026-02-01 08:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی شده در')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نمره')),
                ('exam_type', models.CharField(choices=[('midterm', 'میان ترم'), ('final', 'فاینل'), ('quiz', 'کوییز'), ('assignment', 'تکلیف')], default='final', max_length=50, verbose_name='نوع امتحان')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='تاریخ امتحان')),
                ('remarks', models.TextField(blank=True, verbose_name='یادداشت')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_scores', to=settings.AUTH_USER_MODEL, verbose_name='ثبت شده توسط')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student', verbose_name='دانش\u200cآموز')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='academics.subject', verbose_name='مضمون')),
            ],
            options={
                'verbose_name': 'نمره دانش\u200cآموز',
                'verbose_name_plural': 'نمرات دانش\u200cآموزان',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'subject', 'exam_type')},
            },
        ),
    ]
